# Generated by Django 5.2.15 on 2026-07-13 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


INGREDIENTS = {
    "Espresso": ("ML", 10000, 1200, 30000),
    "Water": ("ML", 30000, 3000, 80000),
    "Milk": ("ML", 30000, 5000, 60000),
    "Condensed Milk": ("ML", 8000, 1200, 20000),
    "Caramel Syrup": ("ML", 8000, 1200, 20000),
    "Chocolate Syrup": ("ML", 8000, 1200, 20000),
    "Strawberry Syrup": ("ML", 8000, 1200, 20000),
    "Mango Syrup": ("ML", 8000, 1200, 20000),
    "Blueberry Syrup": ("ML", 8000, 1200, 20000),
    "Green Apple Syrup": ("ML", 8000, 1200, 20000),
    "Sparkling Water": ("ML", 40000, 5000, 90000),
    "Matcha Powder": ("G", 1500, 250, 4000),
    "Chocolate Powder": ("G", 3000, 400, 8000),
    "Chocnut": ("G", 2500, 400, 7000),
    "Fruit Syrup": ("ML", 8000, 1200, 20000),
}

RECIPES = {
    "Espresso": [("Espresso", 30)],
    "Americano": [("Espresso", 60), ("Water", 180)],
    "Cappuccino": [("Espresso", 30), ("Milk", 150)],
    "Spanish Latte": [("Espresso", 30), ("Milk", 150), ("Condensed Milk", 30)],
    "Caramel Macchiato": [("Espresso", 30), ("Milk", 150), ("Caramel Syrup", 20)],
    "Chocnut Latte": [("Espresso", 30), ("Milk", 150), ("Chocnut", 20)],
    "Triple Chocolate Latte": [("Espresso", 30), ("Milk", 150), ("Chocolate Powder", 25), ("Chocolate Syrup", 20)],
    "Classic Matcha": [("Matcha Powder", 6), ("Milk", 180)],
    "Dirty Matcha": [("Matcha Powder", 6), ("Milk", 160), ("Espresso", 30)],
    "Chocnut Matcha": [("Matcha Powder", 6), ("Milk", 160), ("Chocnut", 20)],
    "Strawberry Matcha": [("Matcha Powder", 6), ("Milk", 150), ("Strawberry Syrup", 30)],
    "Sparkling Mango": [("Sparkling Water", 250), ("Mango Syrup", 30)],
    "Sparkling Strawberry": [("Sparkling Water", 250), ("Strawberry Syrup", 30)],
    "Sparkling Blueberry": [("Sparkling Water", 250), ("Blueberry Syrup", 30)],
    "Sparkling Green Apple": [("Sparkling Water", 250), ("Green Apple Syrup", 30)],
}


def infer_recipe(product):
    if product.name in RECIPES:
        return RECIPES[product.name]
    name = product.name.lower()
    category_name = product.category.name.lower() if product.category else ""
    if "soda" in category_name or "sparkling" in name:
        return [("Sparkling Water", 250), ("Fruit Syrup", 30)]
    if "matcha" in name:
        return [("Matcha Powder", 6), ("Milk", 160)]
    if "latte" in name or "cappuccino" in name or "coffee" in category_name:
        return [("Espresso", 30), ("Milk", 150)]
    return []


def seed_ingredients_and_recipes(apps, schema_editor):
    Category = apps.get_model("inventory", "Category")
    Product = apps.get_model("inventory", "Product")
    Ingredient = apps.get_model("inventory", "Ingredient")
    RecipeIngredient = apps.get_model("inventory", "RecipeIngredient")

    raw_category, _ = Category.objects.get_or_create(
        name="Raw Ingredients",
        defaults={"description": "Ingredient stock used by POS drink recipes"},
    )

    ingredients = {}
    for name, defaults in INGREDIENTS.items():
        base_unit, stock_quantity, minimum_stock_level, maximum_stock_level = defaults
        ingredient, _ = Ingredient.objects.get_or_create(
            name=name,
            defaults={
                "base_unit": base_unit,
                "stock_quantity": stock_quantity,
                "minimum_stock_level": minimum_stock_level,
                "maximum_stock_level": maximum_stock_level,
                "category": raw_category,
                "storage_location": "Main Bar",
            },
        )
        ingredients[name] = ingredient

    for product in Product.objects.filter(is_cafe_item=True).select_related("category"):
        for ingredient_name, quantity in infer_recipe(product):
            ingredient = ingredients.get(ingredient_name)
            if ingredient:
                RecipeIngredient.objects.update_or_create(
                    product=product,
                    ingredient=ingredient,
                    defaults={"quantity": Decimal(str(quantity))},
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_batch_number_product_expiration_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('base_unit', models.CharField(choices=[('G', 'g'), ('ML', 'mL')], max_length=2)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maximum_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=80)),
                ('storage_location', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='inventory.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('input_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('input_unit', models.CharField(blank=True, max_length=3)),
                ('reason', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.ingredient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in ingredient base unit per drink', max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'ingredient')},
            },
        ),
        migrations.RunPython(seed_ingredients_and_recipes, noop_reverse),
    ]
