# Generated by Django 5.2.15 on 2026-07-21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_inventory_children(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    Supplier = apps.get_model('inventory', 'Supplier')
    Product = apps.get_model('inventory', 'Product')
    Ingredient = apps.get_model('inventory', 'Ingredient')
    RecipeIngredient = apps.get_model('inventory', 'RecipeIngredient')
    StockMovement = apps.get_model('inventory', 'StockMovement')
    IngredientStockMovement = apps.get_model('inventory', 'IngredientStockMovement')
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    InventoryEvent = apps.get_model('inventory', 'InventoryEvent')

    raw_category, _ = Category.objects.get_or_create(name='Raw Ingredients', defaults={'description': 'Ingredient stock used by recipes'})

    suppliers = {
        supplier.id: {
            'id': supplier.id,
            'name': supplier.name,
            'contact_person': supplier.contact_person,
            'email': supplier.email,
            'phone': supplier.phone,
            'address': supplier.address,
        }
        for supplier in Supplier.objects.all()
    }

    for product in Product.objects.select_related('category', 'supplier'):
        product.item_type = 'PRODUCT'
        product.category_name = product.category.name if product.category_id else ''
        product.category_description = product.category.description if product.category_id else ''
        product.supplier_details = suppliers.get(product.supplier_id, {})
        product.minimum_stock_level = product.reorder_point
        product.stock_quantity = product.stock_level
        product.save(update_fields=['item_type', 'category_name', 'category_description', 'supplier_details', 'minimum_stock_level', 'stock_quantity'])

    ingredient_product_ids = {}
    for ingredient in Ingredient.objects.all().order_by('id'):
        product = Product.objects.create(
            name=ingredient.name,
            item_type='INGREDIENT',
            category_id=ingredient.category_id or raw_category.id,
            category_name=ingredient.category.name if ingredient.category_id else 'Raw Ingredients',
            category_description=ingredient.category.description if ingredient.category_id else raw_category.description,
            supplier_id=ingredient.supplier_id,
            supplier_details=suppliers.get(ingredient.supplier_id, {}),
            base_unit=ingredient.base_unit,
            stock_quantity=ingredient.stock_quantity,
            minimum_stock_level=ingredient.minimum_stock_level,
            maximum_stock_level=ingredient.maximum_stock_level,
            expiration_date=ingredient.expiration_date,
            purchase_date=ingredient.purchase_date,
            batch_number=ingredient.batch_number,
            storage_location=ingredient.storage_location,
            price=0,
            cost=0,
            stock_level=0,
            is_cafe_item=False,
            is_active=True,
        )
        ingredient_product_ids[ingredient.id] = product.id

    recipe_map = {}
    for row in RecipeIngredient.objects.all().order_by('id'):
        ingredient_product_id = ingredient_product_ids.get(row.ingredient_id)
        if not ingredient_product_id:
            continue
        recipe_map.setdefault(row.product_id, []).append({
            'id': row.id,
            'product': row.product_id,
            'ingredient': ingredient_product_id,
            'ingredient_name': row.ingredient.name,
            'quantity': str(row.quantity),
            'base_unit': row.ingredient.base_unit,
        })
    for product_id, recipe_items in recipe_map.items():
        Product.objects.filter(pk=product_id).update(recipe_data=recipe_items)

    for movement in StockMovement.objects.all().order_by('id'):
        InventoryEvent.objects.create(
            event_type='STOCK_MOVEMENT',
            product_id=movement.product_id,
            user_id=movement.user_id,
            movement_type=movement.movement_type,
            quantity=movement.quantity,
            reason=movement.reason,
            payload={'legacy_stock_movement_id': movement.id},
            created_at=movement.timestamp,
        )

    for movement in IngredientStockMovement.objects.all().order_by('id'):
        InventoryEvent.objects.create(
            event_type='INGREDIENT_MOVEMENT',
            product_id=ingredient_product_ids.get(movement.ingredient_id),
            user_id=movement.user_id,
            movement_type=movement.movement_type,
            quantity=movement.quantity,
            input_quantity=movement.input_quantity,
            input_unit=movement.input_unit,
            reason=movement.reason,
            payload={'legacy_ingredient_movement_id': movement.id},
            created_at=movement.timestamp,
        )

    for po in PurchaseOrder.objects.prefetch_related('items').order_by('id'):
        InventoryEvent.objects.create(
            event_type='PURCHASE_ORDER',
            supplier_id=po.supplier_id,
            supplier_details=suppliers.get(po.supplier_id, {}),
            status=po.status,
            notes=po.notes,
            items=[
                {
                    'id': item.id,
                    'product': item.product_id,
                    'product_id': item.product_id,
                    'product_name': item.product.name,
                    'quantity': item.quantity,
                    'cost_price': str(item.cost_price),
                }
                for item in po.items.all()
            ],
            created_at=po.created_at,
            updated_at=po.updated_at,
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('inventory', '0005_product_is_active_deactivate_glossy_a4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(model_name='product', name='base_unit', field=models.CharField(blank=True, max_length=2)),
        migrations.AddField(model_name='product', name='category_description', field=models.TextField(blank=True)),
        migrations.AddField(model_name='product', name='category_name', field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='product', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now)),
        migrations.AddField(model_name='product', name='item_type', field=models.CharField(choices=[('PRODUCT', 'Product'), ('INGREDIENT', 'Ingredient')], default='PRODUCT', max_length=16)),
        migrations.AddField(model_name='product', name='minimum_stock_level', field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name='product', name='recipe_data', field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name='product', name='stock_quantity', field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name='product', name='supplier_details', field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name='product', name='updated_at', field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(model_name='product', name='is_cafe_item', field=models.BooleanField(default=True)),
        migrations.AlterField(model_name='product', name='maximum_stock_level', field=models.DecimalField(decimal_places=2, default=100, max_digits=12)),
        migrations.AlterField(model_name='product', name='price', field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STOCK_MOVEMENT', 'Stock movement'), ('INGREDIENT_MOVEMENT', 'Ingredient movement'), ('PURCHASE_ORDER', 'Purchase order')], max_length=32)),
                ('movement_type', models.CharField(blank=True, max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('input_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('input_unit', models.CharField(blank=True, max_length=3)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('supplier', models.PositiveIntegerField(blank=True, null=True)),
                ('supplier_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inventory.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.RunPython(migrate_inventory_children, migrations.RunPython.noop),
        migrations.AlterField(model_name='product', name='category', field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AlterField(model_name='product', name='supplier', field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AlterUniqueTogether(name='recipeingredient', unique_together=None),
        migrations.RemoveField(model_name='ingredient', name='category'),
        migrations.RemoveField(model_name='ingredient', name='supplier'),
        migrations.RemoveField(model_name='ingredientstockmovement', name='ingredient'),
        migrations.RemoveField(model_name='ingredientstockmovement', name='user'),
        migrations.RemoveField(model_name='recipeingredient', name='ingredient'),
        migrations.RemoveField(model_name='recipeingredient', name='product'),
        migrations.RemoveField(model_name='stockmovement', name='product'),
        migrations.RemoveField(model_name='stockmovement', name='user'),
        migrations.RemoveField(model_name='purchaseorder', name='supplier'),
        migrations.RemoveField(model_name='purchaseorderitem', name='purchase_order'),
        migrations.RemoveField(model_name='purchaseorderitem', name='product'),
        migrations.DeleteModel(name='Category'),
        migrations.DeleteModel(name='Ingredient'),
        migrations.DeleteModel(name='IngredientStockMovement'),
        migrations.DeleteModel(name='PurchaseOrder'),
        migrations.DeleteModel(name='PurchaseOrderItem'),
        migrations.DeleteModel(name='RecipeIngredient'),
        migrations.DeleteModel(name='StockMovement'),
        migrations.DeleteModel(name='Supplier'),
    ]
