# Generated by Codex on 2026-07-21

from django.db import migrations, models
import django.db.models.functions.text


def disambiguate_payment_references(apps, schema_editor):
    Payment = apps.get_model('payment', 'Payment')
    seen = set()

    queryset = Payment.objects.filter(reference_number__isnull=False).exclude(reference_number='').order_by('payment_type', 'id')
    for payment in queryset:
        reference = (payment.reference_number or '').strip()
        key = (payment.payment_type, reference.casefold())
        if key in seen:
            suffix = f"-DUP-{payment.id}"
            reference = f"{reference[:100 - len(suffix)]}{suffix}"
            key = (payment.payment_type, reference.casefold())
            while key in seen:
                suffix = f"-DUP-{payment.id}-{len(seen)}"
                reference = f"{(payment.reference_number or '').strip()[:100 - len(suffix)]}{suffix}"
                key = (payment.payment_type, reference.casefold())
            payment.reference_number = reference
            payment.save(update_fields=['reference_number'])
        seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(disambiguate_payment_references, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('reference_number'),
                'payment_type',
                condition=models.Q(reference_number__isnull=False) & ~models.Q(reference_number=''),
                name='payment_type_reference_ci_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(
                condition=models.Q(idempotency_key__isnull=False) & ~models.Q(idempotency_key=''),
                fields=('payment_type', 'idempotency_key'),
                name='payment_type_idempotency_unique',
            ),
        ),
    ]
