# Generated by Django 5.2.15 on 2026-07-21 10:17

from django.db import migrations


def archive_notifications(apps, schema_editor):
    AuditLog = apps.get_model('audit', 'AuditLog')
    Notification = apps.get_model('notifications', 'Notification')
    for row in Notification.objects.all():
        AuditLog.objects.create(
            user_id=row.user_id,
            action='NOTIFICATION_ARCHIVE',
            description=row.title,
            metadata={
                'title': row.title,
                'message': row.message,
                'is_read': row.is_read,
                'created_at': row.created_at.isoformat() if row.created_at else None,
                'legacy_notification_id': row.id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_metadata'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(archive_notifications, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
