# Generated by Codex on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
