# Generated by Django 5.2.15 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_normalize_customer_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_method',
            field=models.CharField(
                choices=[
                    ('FORM', 'Registration form'),
                    ('GOOGLE', 'Google authentication'),
                    ('ADMIN', 'Created by admin'),
                    ('LEGACY', 'Existing account'),
                ],
                default='LEGACY',
                max_length=10,
            ),
        ),
    ]
