# Generated by Django 5.2.15 on 2026-07-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasting', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandprediction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_predictions', to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='demandprediction',
            unique_together={('product', 'target_date')},
        ),
    ]
