# Generated by Django 5.2.15 on 2026-07-21 10:17

from django.db import migrations


def archive_forecast_data(apps, schema_editor):
    AuditLog = apps.get_model('audit', 'AuditLog')
    SalesPrediction = apps.get_model('forecasting', 'SalesPrediction')
    DemandPrediction = apps.get_model('forecasting', 'DemandPrediction')
    for row in SalesPrediction.objects.all():
        AuditLog.objects.create(
            action='SALES_PREDICTION_ARCHIVE',
            description=f"Sales prediction {row.target_date}",
            metadata={
                'target_date': row.target_date.isoformat(),
                'predicted_sales': str(row.predicted_sales),
                'lower_bound': str(row.lower_bound) if row.lower_bound is not None else None,
                'upper_bound': str(row.upper_bound) if row.upper_bound is not None else None,
                'legacy_salesprediction_id': row.id,
            },
        )
    for row in DemandPrediction.objects.select_related('product'):
        AuditLog.objects.create(
            action='DEMAND_PREDICTION_ARCHIVE',
            description=f"Demand prediction {row.target_date}",
            metadata={
                'target_date': row.target_date.isoformat(),
                'product_id': row.product_id,
                'product_name': row.product.name if row.product_id else '',
                'predicted_quantity': row.predicted_quantity,
                'legacy_demandprediction_id': row.id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_metadata'),
        ('forecasting', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(archive_forecast_data, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='demandprediction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='demandprediction',
            name='product',
        ),
        migrations.DeleteModel(
            name='SalesPrediction',
        ),
        migrations.DeleteModel(
            name='DemandPrediction',
        ),
    ]
