# Generated by Django 5.2.15 on 2026-07-21 10:17

from django.db import migrations


def archive_gallery_data(apps, schema_editor):
    AuditLog = apps.get_model('audit', 'AuditLog')
    GalleryImage = apps.get_model('gallery', 'GalleryImage')
    for image in GalleryImage.objects.all():
        AuditLog.objects.create(
            action='GALLERY_IMAGE_ARCHIVE',
            description=image.title,
            metadata={
                'title': image.title,
                'category': image.category,
                'image': image.image.name if image.image else '',
                'alt_text': image.alt_text,
                'caption': image.caption,
                'is_featured': image.is_featured,
                'sort_order': image.sort_order,
                'legacy_galleryimage_id': image.id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_metadata'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(archive_gallery_data, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
