# Generated by Django 5.2.15 on 2026-07-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash')], default='CASH', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Reference ID for GCash payments', max_length=100, null=True),
        ),
    ]
