# Generated by Django 5.2.15 on 2026-07-21

from django.db import migrations, models


def migrate_booking_children(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    BookingItem = apps.get_model('booking', 'BookingItem')
    BookingChangeLog = apps.get_model('booking', 'BookingChangeLog')
    BookingPayment = apps.get_model('booking', 'BookingPayment')
    Payment = apps.get_model('payment', 'Payment')

    for booking in Booking.objects.all():
        booking.items = [
            {
                'id': item.id,
                'name': item.name,
                'price': str(item.price),
                'quantity': item.quantity,
            }
            for item in BookingItem.objects.filter(booking_id=booking.id).order_by('id')
        ]
        booking.change_history = [
            {
                'id': row.id,
                'changed_by': row.changed_by_id,
                'changed_by_name': '',
                'old_values': row.old_values,
                'new_values': row.new_values,
                'reason': row.reason,
                'created_at': row.created_at.isoformat() if row.created_at else None,
            }
            for row in BookingChangeLog.objects.filter(booking_id=booking.id).order_by('-created_at')
        ]
        booking.save(update_fields=['items', 'change_history'])

    for old in BookingPayment.objects.all().order_by('id'):
        Payment.objects.create(
            payment_type='BOOKING',
            booking_id=old.booking_id,
            amount=old.amount,
            method='GCASH',
            reference_number=old.reference_number,
            receipt=old.receipt,
            status=old.status,
            paid_at=old.paid_at,
            verified_by_id=old.verified_by_id,
            verified_at=old.verified_at,
            admin_note=old.admin_note,
            metadata={'legacy_booking_payment_id': old.id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingchangelog'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='change_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(migrate_booking_children, migrations.RunPython.noop),
        migrations.RemoveField(model_name='bookingitem', name='booking'),
        migrations.RemoveField(model_name='bookingpayment', name='booking'),
        migrations.RemoveField(model_name='bookingpayment', name='verified_by'),
        migrations.DeleteModel(name='BookingChangeLog'),
        migrations.DeleteModel(name='BookingItem'),
        migrations.DeleteModel(name='BookingPayment'),
    ]
