# Generated by Codex on 2026-07-21

from django.db import migrations, models
import django.db.models.functions.text


ACTIVE_STATUSES = {'PENDING', 'CONFIRMED', 'CONFIRMED_DP'}


def disambiguate_services_and_packages(apps, schema_editor):
    Service = apps.get_model('booking', 'Service')
    Package = apps.get_model('booking', 'Package')

    seen_services = set()
    for service in Service.objects.all().order_by('id'):
        key = (service.name or '').strip().casefold()
        if key and key in seen_services:
            suffix = f" #{service.id}"
            service.name = f"{(service.name or '').strip()[:100 - len(suffix)]}{suffix}"
            service.save(update_fields=['name'])
            key = service.name.casefold()
        if key:
            seen_services.add(key)

    seen_packages = set()
    for package in Package.objects.all().order_by('service_id', 'id'):
        key = (package.service_id, (package.name or '').strip().casefold())
        if key[1] and key in seen_packages:
            suffix = f" #{package.id}"
            package.name = f"{(package.name or '').strip()[:100 - len(suffix)]}{suffix}"
            package.save(update_fields=['name'])
            key = (package.service_id, package.name.casefold())
        if key[1]:
            seen_packages.add(key)


def cancel_duplicate_active_slots(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    seen_slots = set()

    queryset = Booking.objects.filter(status__in=ACTIVE_STATUSES).order_by(
        'scheduled_date',
        'scheduled_time',
        'created_at',
        'id',
    )
    for booking in queryset:
        key = (booking.scheduled_date, booking.scheduled_time)
        if key not in seen_slots:
            seen_slots.add(key)
            continue

        history = list(getattr(booking, 'change_history', None) or [])
        history.insert(0, {
            'id': len(history) + 1,
            'changed_by': None,
            'changed_by_name': 'System',
            'old_values': {'status': booking.status},
            'new_values': {'status': 'CANCELLED'},
            'reason': 'Cancelled automatically while enforcing unique active booking slots.',
            'created_at': None,
        })
        booking.status = 'CANCELLED'
        booking.change_history = history
        booking.save(update_fields=['status', 'change_history'])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_compact_booking_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(disambiguate_services_and_packages, migrations.RunPython.noop),
        migrations.RunPython(cancel_duplicate_active_slots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('name'),
                name='booking_service_name_ci_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(
                'service',
                django.db.models.functions.text.Lower('name'),
                name='booking_package_service_name_ci_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=['PENDING', 'CONFIRMED', 'CONFIRMED_DP']),
                fields=('scheduled_date', 'scheduled_time'),
                name='booking_active_slot_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(
                condition=models.Q(idempotency_key__isnull=False) & ~models.Q(idempotency_key=''),
                fields=('customer', 'idempotency_key'),
                name='booking_customer_idempotency_unique',
            ),
        ),
    ]
