# Generated by Django 5.2.15 on 2026-07-21 10:17

from django.db import migrations


def archive_chatbot_data(apps, schema_editor):
    AuditLog = apps.get_model('audit', 'AuditLog')
    ChatbotFAQ = apps.get_model('chatbot', 'ChatbotFAQ')
    ChatbotLog = apps.get_model('chatbot', 'ChatbotLog')
    for faq in ChatbotFAQ.objects.all():
        AuditLog.objects.create(
            action='FAQ_RECORD',
            description=faq.question,
            metadata={'question': faq.question, 'answer': faq.answer, 'tags': faq.tags, 'active': True, 'legacy_chatbotfaq_id': faq.id},
        )
    for log in ChatbotLog.objects.all():
        AuditLog.objects.create(
            user_id=log.user_id,
            action='CHATBOT_QUERY_ARCHIVE',
            description=log.question,
            metadata={'response': log.response, 'session_id': log.session_id, 'legacy_chatbotlog_id': log.id},
            timestamp=log.timestamp,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_metadata'),
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(archive_chatbot_data, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ChatbotFAQ',
        ),
        migrations.DeleteModel(
            name='ChatbotLog',
        ),
    ]
