# Generated by Django 5.2.15 on 2026-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pos_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('booking_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transaction_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Sales Summaries',
                'ordering': ['-date'],
            },
        ),
    ]
