# Generated by Django 5.2.15 on 2026-07-21 10:17

from django.db import migrations


def archive_sales_data(apps, schema_editor):
    AuditLog = apps.get_model('audit', 'AuditLog')
    DailySalesSummary = apps.get_model('sales', 'DailySalesSummary')
    for row in DailySalesSummary.objects.all():
        AuditLog.objects.create(
            action='DAILY_SALES_SUMMARY_ARCHIVE',
            description=f"Daily sales summary {row.date}",
            metadata={
                'date': row.date.isoformat(),
                'total_revenue': str(row.total_revenue),
                'pos_revenue': str(row.pos_revenue),
                'booking_revenue': str(row.booking_revenue),
                'transaction_count': row.transaction_count,
                'legacy_dailysalessummary_id': row.id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_metadata'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(archive_sales_data, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='DailySalesSummary',
        ),
    ]
